# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: PR Preview for GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  # Build & deploy previews on PR open/update
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          VITE_BASE_URL: /docs-pr-preview/pr-preview/pr-${{ github.event.pull_request.number }}
        run: pnpm run docs:build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .vitepress/dist